/*
 * This file has been automatically generated by cffi-grovel.
 * Do not edit it by hand.
 */

#define ____hoge___ sizeof(int)

#include <grovel/common.h>

int main(int argc, char**argv) {
  int autotype_tmp;
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;
  fprintf(output, ";;;; This file has been automatically generated by "
                  "cffi-grovel.\n;;;; Do not edit it by hand.\n\n");
  fputs("(cl:in-package #:HOGE.FFI)\n\n", output);

  /* constant section for +WHAT+ */
#ifdef ____hoge___
  fputs("(cl:defconstant ", output);
  fputs("+what+", output);
  fputs(" ", output);
  if(_64_BIT_VALUE_FITS_SIGNED_P(____hoge___))
    fprintf(output, "%lli", (long long signed) ____hoge___);
  else
    fprintf(output, "%llu", (long long unsigned) ____hoge___);
  fputs(")\n", output);
#else
  fputs("(cl:warn 'cffi-grovel:missing-definition :name '+WHAT+)\n", output);
#endif

  if  (output != stdout)
    fclose(output);
  return 0;
}
