(com.ral.project-packages:defproject
 (#:project       #:com.ral.project-packages)
 (#:um            #:com.ral.useful-macros)
 (#:def*          #:com.ral.useful-macros.def-extensions)
 (#:aop           #:com.ral.useful-macros.dflet)
 (#:uuidgen       #:com.ral.uuidgen)
 (#:cps           #:com.ral.cps)

 (#:plt           #:plotter)
 (#:vm            #:vmath)
 (#:vmath         #:com.ral.vectorized-math)
 (#:vops          #:vector-ops)
 (#:vector-ops    #:com.ral.vector-ops)
 (#:interpolation #:com.ral.interpolation)
 (#:fft           #:com.ral.fft)
 (#:sfft          #:com.ral.sfft)
 (#:dfft          #:com.ral.dfft)
 (#:fft2d         #:com.ral.fft2d)
 (#:roots         #:com.ral.roots)
 (#:lmfit         #:com.ral.lmfit)
 (#:linfit        #:com.ral.linfit)

 (#:mpc           #:mpcompat)
 (#:mpcompat      #:com.ral.mpcompat)
 (#:ca            #:c-arrays)
 (#:c-arrays      #:com.ral.c-arrays)
 (#:engfmt        #:com.ral.useful-macros.engfmt)
 (#:uuid          #:com.ral.uuid)
 (#:usec          #:com.ral.usec)

 (#:scatter-vec   #:com.ral.scatter-vec)
 (#:mgdbuf        #:com.ral.managed-buffers)
 (#:ubstream      #:ubyte-streams)
 (#:ubyte-streams #:com.ral.ubyte-streams)
 (#:self-sync     #:com.ral.self-sync)
 (#:loenc         #:com.ral.lisp-object-encoder)
 (#:sets          #:com.ral.rb-trees.sets)
 (#:maps          #:com.ral.rb-trees.maps)
 (#:ref           #:com.ral.ref)
 (#:priq          #:com.ral.prio-queue)
 (#:ord           #:com.ral.ord)
 (#:orderable     #:com.ral.orderable)

 (#:ac            #:actors)
 (#:actors        #:com.ral.actors)
 (#:vrepr         #:vec-repr)
 (#:vec-repr      #:com.ral.vec-repr)
 (#:edec          #:com.ral.crypto.edwards-ecc)
 (#:modmath       #:com.ral.crypto.modular-arith)
 (#:hash          #:com.ral.crypto.hash)
 (#:prng          #:com.ral.crypto.prng)
 (#:kdf           #:com.ral.crypto.kdf)
 (#:ciphers       #:com.ral.crypto.ciphers)
 (#:primes        #:com.ral.crypto.primes)
 (#:pbc           #:com.ral.crypto.pbc-interface)
 (#:core-crypto   #:com.ral.crypto.core-crypto)
 )

